#include "acp/blender_bridge.hpp"

#include "acp/obj.hpp"

#include <fstream>
#include <sstream>

namespace acp::blender {
namespace {

std::string python_string(const std::filesystem::path& path) {
    const std::string raw = path.generic_string();
    std::string escaped;
    escaped.reserve(raw.size() + 8);
    for (const char ch : raw) {
        switch (ch) {
            case '\\': escaped += "\\\\"; break;
            case '\'': escaped += "\\'"; break;
            case '\n': escaped += "\\n"; break;
            case '\r': escaped += "\\r"; break;
            default: escaped += ch; break;
        }
    }
    return "'" + escaped + "'";
}

std::string quote_command_arg(const std::filesystem::path& path) {
    const std::string raw = path.string();
    std::string quoted = "\"";
    for (const char ch : raw) {
        if (ch == '\"') {
            quoted += "\\\"";
        } else {
            quoted += ch;
        }
    }
    quoted += "\"";
    return quoted;
}

} // namespace

std::string import_script(
    const std::filesystem::path& obj_path,
    const std::optional<std::filesystem::path>& save_blend_path) {

    std::ostringstream out;
    out <<
R"(# Generated by Auto CAD Pro.
import bpy

OBJ_PATH = )" << python_string(obj_path) << R"(
SAVE_BLEND_PATH = )";
    if (save_blend_path.has_value()) {
        out << python_string(*save_blend_path);
    } else {
        out << "None";
    }

    out << R"(

# Auto CAD Pro currently transfers drawing units 1:1 and marks the scene Metric.
scene = bpy.context.scene
scene.unit_settings.system = 'METRIC'
scene.unit_settings.scale_length = 1.0

# Import across current Blender versions, with a fallback for older versions.
if hasattr(bpy.ops.wm, "obj_import"):
    bpy.ops.wm.obj_import(filepath=OBJ_PATH)
else:
    bpy.ops.import_scene.obj(filepath=OBJ_PATH)

imported = list(bpy.context.selected_objects)

CATEGORY_PREFIXES = {
    "Wall_": "ACP_Walls",
    "Slab_": "ACP_Slabs",
    "Column_": "ACP_Columns",
    "Beam_": "ACP_Beams",
    "Door_": "ACP_Doors",
    "Window_": "ACP_Windows",
    "Roof_": "ACP_Roofs",
    "Stair_": "ACP_Stairs",
}

def ensure_collection(name):
    collection = bpy.data.collections.get(name)
    if collection is None:
        collection = bpy.data.collections.new(name)
        scene.collection.children.link(collection)
    return collection

def classify(name):
    for prefix, collection_name in CATEGORY_PREFIXES.items():
        if name.startswith(prefix):
            return prefix[:-1], collection_name
    return "Generic", "ACP_Generic"

for obj in imported:
    kind, collection_name = classify(obj.name)
    obj["auto_cad_pro_source"] = True
    obj["auto_cad_pro_kind"] = kind
    target = ensure_collection(collection_name)
    for collection in list(obj.users_collection):
        collection.objects.unlink(obj)
    target.objects.link(obj)

if SAVE_BLEND_PATH:
    bpy.ops.wm.save_as_mainfile(filepath=SAVE_BLEND_PATH)
)";

    return out.str();
}

std::optional<Bundle> write_bundle(
    const std::filesystem::path& directory,
    const model3d::Scene& scene,
    const std::optional<std::filesystem::path>& save_blend_path) {

    std::error_code error;
    std::filesystem::create_directories(directory, error);
    if (error) {
        return std::nullopt;
    }

    const std::filesystem::path obj_path =
        directory / "auto_cad_pro_scene.obj";
    const std::filesystem::path script_path =
        directory / "import_auto_cad_pro.py";

    if (!obj::save(obj_path, scene)) {
        return std::nullopt;
    }

    std::ofstream script(script_path, std::ios::binary | std::ios::trunc);
    if (!script) {
        return std::nullopt;
    }
    const std::string content = import_script(obj_path, save_blend_path);
    script.write(content.data(), static_cast<std::streamsize>(content.size()));
    script.flush();
    if (!script.good()) {
        return std::nullopt;
    }

    return Bundle{obj_path, script_path};
}

std::string command_line(
    const std::filesystem::path& blender_executable,
    const std::filesystem::path& script_path) {

    return quote_command_arg(blender_executable) +
           " --python " +
           quote_command_arg(script_path);
}

} // namespace acp::blender
